version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - afuscella-bot
  assignees:
  - afuscella-bot
  labels:
  - "status: review requested"
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.10.3
    - 3.10.5
    - 3.5.2
    - 3.6.3
    - 3.6.7
    - 3.7.0
    - 3.9.0
    - 3.9.2
    - 4.0.0
    - 4.0.2
    - 4.0.3
    - 4.1.10
    - 4.1.2
    - 4.1.3
    - 4.1.5
    - 4.1.6
    - 4.1.8
    - 4.1.9
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: next
    versions:
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.2
    - 10.1.3
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
